In [ ]:
import numpy as np

In [ ]:
arr = np.array({1,2,3,4})
print(np.size(arr))

1


In [ ]:
print(arr)

{1, 2, 3, 4}


In [ ]:
l = [[1,2],[3,4]]
l

[[1, 2], [3, 4]]

In [ ]:
np.array(l)

array([[1, 2],
       [3, 4]])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

ARRAY METHODS

In [ ]:
arr.sum()
arr.min()

np.int64(1)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
arr.min()


np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
np.mean(arr)

np.float64(5.0)

In [ ]:
np.median(arr)

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
arr.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
num = np.arange(11,21)
num

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
print(num[2])
print(num[2:5])
print(num[2:])
print(num[2::2])

13
[13 14 15]
[13 14 15 16 17 18 19 20]
[13 15 17 19]


In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0:3,1:4]
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])